### ISSUE TITLE
Maximum voltage for powering the board

### ISSUE THREAD

**Issue by luky133** [ajvdw/EMSBusShield#1]
I have question about max voltage for powering the board. I used my lab power supply and if I set-up voltage to 12V an ESP board is bricked after few second (I can’t connect to ESP-EMS via Wi-Fi). If I used voltage between 7-9V ESP board working. I measured voltage on 78L05 and there is still 5V, but if I used 12V 78L05  is too hot (+70°C). Is this a bug or a feature?

**Comment by ajvdw** [comment]
It depends on the esp board. A Lolin ESP32 S2 only supports max 5V on the VBUS. Most boards have a max of 5V input.

Just power the board through the USB port and it should work fine.
Typically a 78L05  is not powerful enough to power a board in AP mode. 
The conversion from 12 to 5 is often done by dissipating the heat .....

If you want 12V as an input, use a step down dc dc converter (https://www.aliexpress.com/item/1005001621785349.html).
The 3.3V can be connected to the output directly skipping the internal conversion from 5V to 3.3V
