### ISSUE TITLE
L1 and L2 inductance values

### ISSUE THREAD

**Issue by olegtarasov** [ajvdw/EMSBusShield#3]
Hi!

Thank you for your project! I'm looking to build the shield, but I'm not sure about L1 and L2 inductance values. In the original schematics at https://emsesp.github.io/docs/EMS-Circuit/#a-breadboard-prototype they have 4.7**uH** inductances, and your schematic has 4.7 **mH**. Is this correct? Or the difference doesn't matter much? 

Thank you!

**Comment by ajvdw** [comment]
> Hi!
> 
> Thank you for your project! I'm looking to build the shield, but I'm not sure about L1 and L2 inductance values. In the original schematics at https://emsesp.github.io/docs/EMS-Circuit/#a-breadboard-prototype they have 4.7**uH** inductances, and your schematic has 4.7 **mH**. Is this correct? Or the difference doesn't matter much?
> 
> Thank you!

You are right! I checked, I ordered the 4.7uH inductors. I will change the design accordingly. Slight issue: I used to work with eagle and was more or less forced by autodesk to switch to Kicad...

**Comment by olegtarasov** [comment]
Thank you for a quick response! I will just get 4.7uH inductors then :)
